#
# Makefile for the ts27010mux driver over USB.
#
#
MODULE_NAME = ts27010mux_usb

obj-y += $(MODULE_NAME).o

$(MODULE_NAME)-objs := ts27010_mux.o \
			ts27010_tty.o \
			ts27010_td.o \
			ts27010_misc.o \
			ts27010_logger.o \
			ts27010_ldisc.o

