#
# Makefile for modem (radio) control drivers
#

obj-$(CONFIG_RADIO_CTRL_CLASS)	+= radio_class.o
obj-$(CONFIG_MDM6600_CTRL)	+= mdm6600_ctrl.o
obj-$(CONFIG_MDM9600_CTRL)	+= mdm9600_ctrl.o
obj-$(CONFIG_WRIGLEY_CTRL)	+= wrigley_ctrl.o
obj-$(CONFIG_QSC6085_CTRL)      += qsc6085_ctrl.o
